"""Criação inicial da tabela Pesquisa

Revision ID: ceb304052287
Revises: 
Create Date: 2025-10-16 14:47:07.790676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ceb304052287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesquisa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('catalog_type', sa.String(length=20), nullable=False),
    sa.Column('research_date', sa.DateTime(), nullable=False),
    sa.Column('responsible_agent', sa.String(length=100), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('prices_collected', sa.JSON(), nullable=False),
    sa.Column('sources_consulted', sa.JSON(), nullable=True),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pesquisa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pesquisa_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_pesquisa_research_date'), ['research_date'], unique=False)

    with op.batch_alter_table('price_research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_research_item_code'))

    op.drop_table('price_research')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_research',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('item_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('item_description', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('search_parameters', sqlite.JSON(), nullable=True),
    sa.Column('collected_prices', sqlite.JSON(), nullable=False),
    sa.Column('statistical_analysis', sqlite.JSON(), nullable=True),
    sa.Column('final_price', sa.FLOAT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('report_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_research_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('pesquisa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pesquisa_research_date'))
        batch_op.drop_index(batch_op.f('ix_pesquisa_item_code'))

    op.drop_table('pesquisa')
    # ### end Alembic commands ###
